### ISSUE TITLE
Reported issue on uploading users installed application information via Pushwoosh SDK

### ISSUE THREAD

**Issue by Nirodha26** [Pushwoosh/pushwoosh-react-native-plugin#124]
We have received a complaint from google play support mentioning that our app is uploading users' installed application  information via Pushwoosh SDK

Following are the specific complaints.

APK Require valid PRIVACY POLICY
Your app is uploading users' installed application  information via Pushwoosh SDK without posting a privacy policy in both the the designated field in the Play Developer Console and from within the Play distributed app itself.

APK Require PROMINENT DISCLOSURE
We've Identified thatyour app is overusing Pushwoosh SDK or library, wooden facilitate the transmission of collection of installed application information without meeting the prominent disclosure guidelines. If necessary, you can consult your SDK provider (s) for further information .

As to our knowledge we do not access user specific details from Pushwoosh. Please let us know further details on above.

**Comment by wfhm** [comment]
@Nirodha26 we have updated the plugin to comply with the new Play Store policy, so all you have to do is to update the plugin and resubmit your app to the Store.

**Comment by SriLakshmi1987** [comment]
Hi ,I also got same issue. I am using Xamarin Android . May I know what Plugin you updated. Thank you

**Comment by Nirodha26** [comment]
@SriLakshmi1987  Privacy policy issue is fixed in pushwoosh-react-native-plugin v6.1.5

**Comment by SriLakshmi1987** [comment]
Hi Nirodha26 , Thank you for your reply. Actually I am using Xamarin . In that I used an Webview to load an URL with  the Parameter PushwooshInApp.Instance.UserId . Then I got the following error


Publishing status: Removed Your app was removed from Google Play and won’t be available to users until you submit a policy compliant update. |   | Publishing status: RemovedYour app was removed from Google Play and won’t be available to users until you submit a policy compliant update. | Publishing status: Removed | Your app was removed from Google Play and won’t be available to users until you submit a policy compliant update.
-- | -- | -- | -- | --
  | Publishing status: RemovedYour app was removed from Google Play and won’t be available to users until you submit a policy compliant update. | Publishing status: Removed | Your app was removed from Google Play and won’t be available to users until you submit a policy compliant update.
Publishing status: Removed
Your app was removed from Google Play and won’t be available to users until you submit a policy compliant update.
Eligibility issues by versionsVersion(s)Eligibility IssueAPK:1APK REQUIRES VALID PRIVACY POLICY​Your app is uploading users' Installed Application information to Pushwoosh SDK, without posting a privacy policy in both the designated field in the Play Developer Console and from within the Play distributed app itself.APK:1APK REQUIRES PROMINENT DISCLOSURE​We’ve identified that your app is using Pushwoosh SDK or library, which facilitates the transmission of collection of Installed Application information without meeting the prominent disclosure guidelines. If necessary, you can consult your SDK provider(s) for further information For further details on the valid prominent disclosure requirement, please review the “Prominent Disclosure & Consent Requirement” section under the User Data policy. |   | Eligibility issues by versionsVersion(s)Eligibility IssueAPK:1APK REQUIRES VALID PRIVACY POLICY​Your app is uploading users' Installed Application information to Pushwoosh SDK, without posting a privacy policy in both the designated field in the Play Developer Console and from within the Play distributed app itself.APK:1APK REQUIRES PROMINENT DISCLOSURE​We’ve identified that your app is using Pushwoosh SDK or library, which facilitates the transmission of collection of Installed Application information without meeting the prominent disclosure guidelines. If necessary, you can consult your SDK provider(s) for further information For further details on the valid prominent disclosure requirement, please review the “Prominent Disclosure & Consent Requirement” section under the User Data policy. | Eligibility issues by versions | Version(s)Eligibility IssueAPK:1APK REQUIRES VALID PRIVACY POLICY​Your app is uploading users' Installed Application information to Pushwoosh SDK, without posting a privacy policy in both the designated field in the Play Developer Console and from within the Play distributed app itself.APK:1APK REQUIRES PROMINENT DISCLOSURE​We’ve identified that your app is using Pushwoosh SDK or library, which facilitates the transmission of collection of Installed Application information without meeting the prominent disclosure guidelines. If necessary, you can consult your SDK provider(s) for further information For further details on the valid prominent disclosure requirement, please review the “Prominent Disclosure & Consent Requirement” section under the User Data policy. | APK:1 | APK REQUIRES VALID PRIVACY POLICY​Your app is uploading users' Installed Application information to Pushwoosh SDK, without posting a privacy policy in both the designated field in the Play Developer Console and from within the Play distributed app itself. | APK:1 | APK REQUIRES PROMINENT DISCLOSURE​We’ve identified that your app is using Pushwoosh SDK or library, which facilitates the transmission of collection of Installed Application information without meeting the prominent disclosure guidelines. If necessary, you can consult your SDK provider(s) for further information For further details on the valid prominent disclosure requirement, please review the “Prominent Disclosure & Consent Requirement” section under the User Data policy.
  | Eligibility issues by versionsVersion(s)Eligibility IssueAPK:1APK REQUIRES VALID PRIVACY POLICY​Your app is uploading users' Installed Application information to Pushwoosh SDK, without posting a privacy policy in both the designated field in the Play Developer Console and from within the Play distributed app itself.APK:1APK REQUIRES PROMINENT DISCLOSURE​We’ve identified that your app is using Pushwoosh SDK or library, which facilitates the transmission of collection of Installed Application information without meeting the prominent disclosure guidelines. If necessary, you can consult your SDK provider(s) for further information For further details on the valid prominent disclosure requirement, please review the “Prominent Disclosure & Consent Requirement” section under the User Data policy. | Eligibility issues by versions | Version(s)Eligibility IssueAPK:1APK REQUIRES VALID PRIVACY POLICY​Your app is uploading users' Installed Application information to Pushwoosh SDK, without posting a privacy policy in both the designated field in the Play Developer Console and from within the Play distributed app itself.APK:1APK REQUIRES PROMINENT DISCLOSURE​We’ve identified that your app is using Pushwoosh SDK or library, which facilitates the transmission of collection of Installed Application information without meeting the prominent disclosure guidelines. If necessary, you can consult your SDK provider(s) for further information For further details on the valid prominent disclosure requirement, please review the “Prominent Disclosure & Consent Requirement” section under the User Data policy. | APK:1 | APK REQUIRES VALID PRIVACY POLICY​Your app is uploading users' Installed Application information to Pushwoosh SDK, without posting a privacy policy in both the designated field in the Play Developer Console and from within the Play distributed app itself. | APK:1 | APK REQUIRES PROMINENT DISCLOSURE​We’ve identified that your app is using Pushwoosh SDK or library, which facilitates the transmission of collection of Installed Application information without meeting the prominent disclosure guidelines. If necessary, you can consult your SDK provider(s) for further information For further details on the valid prominent disclosure requirement, please review the “Prominent Disclosure & Consent Requirement” section under the User Data policy.
Eligibility issues by versions
Version(s)Eligibility IssueAPK:1APK REQUIRES VALID PRIVACY POLICY​Your app is uploading users' Installed Application information to Pushwoosh SDK, without posting a privacy policy in both the designated field in the Play Developer Console and from within the Play distributed app itself.APK:1APK REQUIRES PROMINENT DISCLOSURE​We’ve identified that your app is using Pushwoosh SDK or library, which facilitates the transmission of collection of Installed Application information without meeting the prominent disclosure guidelines. If necessary, you can consult your SDK provider(s) for further information For further details on the valid prominent disclosure requirement, please review the “Prominent Disclosure & Consent Requirement” section under the User Data policy. | APK:1 | APK REQUIRES VALID PRIVACY POLICY​Your app is uploading users' Installed Application information to Pushwoosh SDK, without posting a privacy policy in both the designated field in the Play Developer Console and from within the Play distributed app itself. | APK:1 | APK REQUIRES PROMINENT DISCLOSURE​We’ve identified that your app is using Pushwoosh SDK or library, which facilitates the transmission of collection of Installed Application information without meeting the prominent disclosure guidelines. If necessary, you can consult your SDK provider(s) for further information For further details on the valid prominent disclosure requirement, please review the “Prominent Disclosure & Consent Requirement” section under the User Data policy.

APK:1 | APK REQUIRES VALID PRIVACY POLICY​Your app is uploading users' Installed Application information to Pushwoosh SDK, without posting a privacy policy in both the designated field in the Play Developer Console and from within the Play distributed app itself.
APK:1 | APK REQUIRES PROMINENT DISCLOSURE​We’ve identified that your app is using Pushwoosh SDK or library, which facilitates the transmission of collection of Installed Application information without meeting the prominent disclosure guidelines. If necessary, you can consult your SDK provider(s) for further information For further details on the valid prominent disclosure requirement, please review the “Prominent Disclosure & Consent Requirement” section under the User Data policy.

**Comment by SriLakshmi1987** [comment]
Hi Nirodha26 , thank you for your reply. Actually I have implemented pushwoosh in the Xamarin android ,In that I used a webview to load  URL,I am sending the  PushwooshInApp.Instance.UserId as a parameter from that URL.

I got the foolowing errors and app is removed from Google play.

APK REQUIRES VALID PRIVACY POLICY​
Your app is uploading users' Installed Application information to Pushwoosh SDK, without posting a privacy policy in both the designated field in the Play Developer Console and from within the Play distributed app itself.

APK REQUIRES PROMINENT DISCLOSURE​
We’ve identified that your app is using Pushwoosh SDK or library, which facilitates the transmission of collection of Installed Application information without meeting the prominent disclosure guidelines. If necessary, you can consult your SDK provider(s) for further information 

For further details on the valid prominent disclosure requirement, please review the “Prominent Disclosure & Consent Requirement” section under the User Data policy.

**Comment by wfhm** [comment]
@SriLakshmi1987 

The updated Xamarin.Droid version that complies with the new Google Play policy is 5.23.0. When resubmitting your app, please also do the following:

* Ensure you have put an updated apk in every release track for your app, not just the production track
* Check to make sure you don’t have any old builds containing branch in your alpha, beta and internal tracks

**Comment by sunehs** [comment]
Hi @wfhm 
We're still having issue with an app using the plugin after updating, it might very well be an issue on our end, but to help us trouble shoot I'd just like to understand this update. The commit for the update only changes the version number, so where is the actual change happening?

**Comment by wfhm** [comment]
@sunehs,

The changes were applied to our native Android SDK. Aside from bumping the plugin version, Pushwoosh dependencies were updated to the 6.2.7 version:

https://github.com/Pushwoosh/pushwoosh-react-native-plugin/blob/6.1.5/src/android/build.gradle#L40

If you have an issue with resubmitting your app after updating Pushwoosh plugin, make sure that you don't have old APKs/app bundles in all releases (including alpha-, beta-, and internal testing tracks). Please note that just deactivating it does not work, you have to remove such artifacts or update your release with a new version.

**Comment by SriLakshmi1987** [comment]
> @SriLakshmi1987
> 
> The updated Xamarin.Droid version that complies with the new Google Play policy is 5.23.0. When resubmitting your app, please also do the following:
> 
> * Ensure you have put an updated apk in every release track for your app, not just the production track
> * Check to make sure you don’t have any old builds containing branch in your alpha, beta and internal tracks

Do you mean Pushwoosh.Xamarin.Droid is 5.23.0? Actually I add the reference Pushwoosh.Xamarin.Droid version  is 5.23.0.But still my app is removed.Kindly help me on this .Tq

**Comment by SriLakshmi1987** [comment]
Hi @wfhm ,after I upgrade Pushwoosh.Xamarin.Droid is 5.23.0 to new version the problem solved. Thank you
