### ISSUE TITLE
undefined is not an Object PushwooshModule.init on ios

### ISSUE THREAD

**Issue by RORrvtech** [Pushwoosh/pushwoosh-react-native-plugin#23]
Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.1.4
  Yarn: 0.27.5
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.2 => 0.55.2
![simulator screen shot - iphone 6 - 2018-04-13 at 14 14 33](https://user-images.githubusercontent.com/28922621/38725642-9d8e75f6-3f25-11e8-9124-591a62e49988.png)

While following installation guide for RN project init project

===========
PACKAGE JSON FOR VERSIONS
{
  "name": "[Hidden*****]",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "linking": "^0.1.0-beta.5",
    "lodash": "^4.17.5",
    "moment": "^2.22.0",
    "native-base": "^2.4.1",
    "path-to-regexp": "^2.2.0",
    "pushwoosh-react-native-plugin": "^5.5.7",
    "react": "16.3.1",
    "react-native": "0.55.2",
    "react-native-maps": "^0.21.0",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^1.5.11",
    "react-navigation-redux-helpers": "^1.0.5",
    "react-redux": "^5.0.7",
    "redux": "^3.7.2",
    "redux-devtools-extension": "^2.13.2",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "babel-jest": "22.4.3",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.3",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

===========

**Comment by wfhm** [comment]
Hi,

Is this issue reproducible on a blank project with only Pushwoosh plugin added? Please note that we could not reproduce it with React Native 0.55.2 and XCode 9.3.

**Comment by wfhm** [comment]
Hi,

Checking it.

**Comment by wfhm** [comment]
Hi,

Following [this guide](https://www.pushwoosh.com/docs/react-native-plugin), I was unable to reproduce this issue on a blank project with Pushwoosh plugin added only.

"dependencies": {
    "pushwoosh-react-native-plugin": "^5.5.7",
    "react": "16.3.1",
    "react-native": "0.55.3"
  }

npm version: 5.8.0, Xcode version: 9.3

Could you please provide us with your index.js, or, better, with a reproducer project?

**Comment by EIrwin** [comment]
Experiencing the same issue

**Comment by RORrvtech** [comment]
EIrwin seems this when you using Podfile pushwoosh doesnot link good in this case. 

Q1) Are you experiencing specific to iOS then follow these steps.
rm -rf ios/Pods
In podfile
  # Pushwoosh
  pod 'pushwoosh-react-native-plugin', :podspec => '../node_modules/pushwoosh-react-native-plugin/pushwoosh-react-native-plugin.podspec'

3) pod install.

if this is case in android. plugin liking is malfunctioned and you have to install it again. 
hint (you can use react-native-git upgrade to eject your app again by deleting ios and android folder)

**Comment by wfhm** [comment]
@RORrvtech 

Could you please confirm that the steps described above solve the issue? Please note that we still could not reproduce it even using Podfile as per your last message.

**Comment by EIrwin** [comment]
We are not using Podfile

**Comment by stereodenis** [comment]
I use Podfile and cocoapods and got the same error
maybe these warnings will help
![image](https://user-images.githubusercontent.com/1406461/39925010-112173bc-553b-11e8-80e6-99f844d83ecd.png)

**Comment by wfhm** [comment]
@EIrwin I had just bumped into this issue, however still no understanding why it happens. Re-installing and linking the plugin solved it for me.

**Comment by fectum89** [comment]
Fixed in 5.6.3. Please update plugin, remove /Pods directory and run `pod install` again.

**Comment by tejparekh** [comment]
The issue is still occuring in 5.17.3 version of repo. 
What is the solution? I have tried multiple times installation and linking. 

thanks
